export const SET_USER = 'setUser'
export const SET_DISPUTES = 'setDisputes'
export const GET_DISPUTE = 'currentDispute'
export const GET_DISPUTE_DETAILS = 'getDisputeDetails'
export const GET_ISSUES = 'getIssues'
